### ISSUE TITLE
My theme isn't visible in your directory #233

### ISSUE THREAD

**Issue by simarmannsingh** [stackbit/jamstackthemes#243]
Hello, thanks for the merge but I couldn't find the theme being shown at https://jamstackthemes.dev/. 
Its being 4 days since PR got merged.  :(

PR #233

**Comment by JugglerX** [comment]
@simarmannsingh This has been fixed. The file was missing a .md extension.

**Comment by simarmannsingh** [comment]
Thanks but the "Live demo" button still doesn't work. The link seems to be working fine.

[https://gatsby-netlifycms-modern-template.netlify.app/](https://gatsby-netlifycms-modern-template.netlify.app/)

**Comment by JugglerX** [comment]
Some themes get iframe issues. I'm aware of this problem but have not decided how to fix it yet.

```
Refused to display 'https://gatsby-netlifycms-modern-template.netlify.app/' in a frame because it set 'X-Frame-Options' to 'deny'.
```

It's possible you can solve the problem by relaxing X-Frame-Options on your side.

**Comment by simarmannsingh** [comment]
Okay. I've see a few more starter templates deployed on Netlify have the same issue. 
I've tried to update the header by creating the _header file in the root directory with X-Frame-Options setting. 
Awaiting a rebuild of your site to fetch the latest commit from my template repo.

**Comment by jmau111** [comment]
@JugglerX hi, there's a delay? can't find mine too.
